"""update

Revision ID: f10349a629d8
Revises: 4eed68723f2c
Create Date: 2024-10-30 16:35:28.835696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10349a629d8'
down_revision: Union[str, None] = '4eed68723f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('rank_1', sa.String(length=45), nullable=True),
    sa.Column('rank_2', sa.String(length=45), nullable=True),
    sa.Column('rank_3', sa.String(length=45), nullable=True),
    sa.Column('rank_4', sa.String(length=45), nullable=True),
    sa.Column('rank_5', sa.String(length=45), nullable=True),
    sa.Column('rank_6', sa.String(length=45), nullable=True),
    sa.Column('rank_7', sa.String(length=45), nullable=True),
    sa.Column('rank_8', sa.String(length=45), nullable=True),
    sa.Column('rank_9', sa.String(length=45), nullable=True),
    sa.Column('rank_10', sa.String(length=45), nullable=True),
    sa.Column('rank_11', sa.String(length=45), nullable=True),
    sa.Column('rank_12', sa.String(length=45), nullable=True),
    sa.Column('rank_13', sa.String(length=45), nullable=True),
    sa.Column('rank_14', sa.String(length=45), nullable=True),
    sa.Column('rank_15', sa.String(length=45), nullable=True),
    sa.Column('rank_16', sa.String(length=45), nullable=True),
    sa.Column('rank_17', sa.String(length=45), nullable=True),
    sa.Column('rank_18', sa.String(length=45), nullable=True),
    sa.Column('rank_19', sa.String(length=45), nullable=True),
    sa.Column('rank_20', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trend')
    op.drop_table('test')
    # ### end Alembic commands ###
